[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
[python]
version = "3.10"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
